// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Kita arahkan ke DIRECT_URL agar CLI Prisma bisa melakukan perubahan skema (db push)
    // langsung ke Supabase melalui Port 5432.
    url: process.env["DIRECT_URL"],
  },
});